### ISSUE TITLE
Uma dica aew

### ISSUE THREAD

**Issue by ChaosAmd** [mateusKoppe/git-guia-basico#1]
Não sei onde será apresentado isto, deixo aqui uma sugestão. 

Uma boa prática, quando se está num time de desenvolvimento é sempre editar o código num branch distinto do master, criado com algum nome significativo. Pushar no master é perdoável quando o projeto tem apenas uma ou duas pessoas, pois nesse caso, usar desses artificios é matar formiga com bazuca.

**Comment by mateusKoppe** [comment]
Vai ser repassado isso sim! :D
Mas para não complicar, a primeiro momento será ensinado a fazer commits, editar, mandar para to remote tudo na master, que é o mais importante a primeiro momento para os alunos salvarem o código e mandar um clone em outro computador. Após entraremos no tópico de boas práticas, branchs, forks, e etc.

Obrigado pela sugestão! :D
